### ISSUE TITLE
L10N: refactor locale generation for List<AbstractUIObject>

### ISSUE THREAD

**Issue by dmtgrinevich** [zebrunner/carina-webdriver#115]
so instead of
component.element=value8

could be generated
page.component[1].element=value1
page.component[2].element=value2
page.component[3].element=value3
...

add var to @Localized, that will determine how unique localized elements name should be
Element: element 
Class: component.element
FullPath: page.component.component.component.element

**Comment by akamarouski** [comment]
wontfix. We should not generate localization for list of elements because order of the elements could be changed
