### ISSUE TITLE
When creating a page, we try to call the constructor to create an object if it inherits AbstractUIObject even if there is no annotation on it

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina-webdriver#68]
Selenium / Appium logic - if an annotation is not specified above the field, we still create an object by By.id, where the field name is the id. A hotfix should be added to ignore fields with AbstractPage type.

**Comment by vdelendik** [comment]
`1.0.1.P1-SNAPSHOT` might be used if hotfix is needed
